repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint functional
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: poetry run black functional
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy functional
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
